### ISSUE TITLE
Put this index.html into gh-pages/docs

### ISSUE THREAD

**Issue by tonglil** [bbatsche/entrust#14]
An index file with this "meta" tag will link together the different versions of the docs into one page: https://github.com/tonglil/entrust/blob/gh-pages/index.html.

Put it in here: https://github.com/bbatsche/entrust/tree/gh-pages/docs

**Comment by tonglil** [comment]
Also you could probably set the repo url to http://bbatsche.github.io/entrust/.

**Comment by bbatsche** [comment]
Completed by db91cb710073d71c3c7fdb32d26bb453a0d9b43c
