### ISSUE TITLE
Refresh Documentation

### ISSUE THREAD

**Issue by bbatsche** [bbatsche/entrust#2]
Comb through and update README
Docblock functions (and update the functions that have been modified)
Config.php comments

**Comment by tonglil** [comment]
I'd like to help you maintain this fork, and perhaps get it merged back one day.
Let me see what I can do next week, maybe set up a github.io page for documentation based on docblock!

**Comment by bbatsche** [comment]
Hey @tonglil, thank you so much for offering to help! Documentation is not exactly my forte and any assistance would be greatly appreciated. At this point, I want to double check all the existing unit tests to make sure they're all in good shape, and make sure the documentation reflects the correct information for this fork and I'll be ready to take the beta tag off.

**Comment by bbatsche** [comment]
Commit 20d9dc66417422774685743be649edfbe7e1001f addressed this issue

**Comment by bbatsche** [comment]
Commit d5b1df52b1f2dde596c07c681e9be286a40d43a9

**Comment by bbatsche** [comment]
At this point I feel pretty confident with the contents of the README.md and documentation. Closing the issue.
